### PR TITLE
 Updated some icons and theming information

### PR DESCRIPTION
**Pull request by TheOneWithTheBraid**
# Updated some icons and theming information
The icon you were using was just the logo of JugendHackt Hamburg.

Updated the icon according to the official JugendHackt colors, mixed with the official PWA design guidelines.
Added a html theme color.
Added larger app icons for HiDPI devices.
Added icons for Safari mobile browsers.

### CODE REVIEW

**Comment by yuki-93** [comment]
Is #1 obsolete with this PR?

**Comment by TheOneWithTheBraid** [comment]
No, I only updated the App icons, but not the icons within the app. Anyway, I'll have a look at #1 .

**Comment by yuki-93** [comment]
Thanks :))

**Review by Mondanzo — APPROVED** [review]
Looks good. 

Approved :+1:

**Pull request merged**
