### PR TITLE
Rework of the dbController

### PR DESCRIPTION
**Pull request by LarsVomMars**
Probably working rework of the dbController.
At least i can't think about any other case throwing errors.

### CODE REVIEW

**Review by marvinborner — CHANGES_REQUESTED** [review]
Seems quite good but please adapt the coding style according to our codacy rules.

**Comment by LarsVomMars** [comment]
I don't wanna :c

**Comment by marvinborner** [comment]
Alright, that should to it. I guess we should wait for @Mondanzo to review the request but it's fine by me.

**Comment by LarsVomMars** [comment]
Finally, maybe the codacy config isn't the best anymore :D

**Pull request merged**
